# Generated by Django 4.2.18 on 2025-11-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='LLM', max_length=20)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
            ],
        ),
    ]
